name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'          # Ignores README.md and any other markdown files
      - 'LICENSE'        # Ignores the license file
      - '.gitignore'     # Ignores git configuration
      - '.github/**'     # Ignores changes to the pipeline script itself

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        # Notice we use github.sha instead of v7! Every push gets a unique, tracked ID.
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/three-dogs-frog-store/retail-repo/retail-app-image:${{ github.sha }}
          docker build --platform linux/amd64 -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Update Compute Engine VM
        run: |
          IMAGE_TAG=us-central1-docker.pkg.dev/three-dogs-frog-store/retail-repo/retail-app-image:${{ github.sha }}
          gcloud compute instances update-container three-dog-one-frog-demo \
            --zone=us-central1-c \
            --container-image=$IMAGE_TAG

      - name: Purge Fastly Cache
        run: |
          curl -X POST -H "Fastly-Key: ${{ secrets.FASTLY_API_KEY }}" \
            https://api.fastly.com/service/${{ secrets.FASTLY_SERVICE_ID }}/purge_all
